name: Generate CV

on:
  workflow_dispatch: ~
  push: ~

jobs:
  deploy:
    name: Generate CV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update -y

      - name: Install wkhtmltopdf and fonts
        run: sudo apt-get install -y wkhtmltopdf fonts-noto

      - name: Generate CV
        run: make -d $GITHUB_WORKSPACE cv

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate CV PDF"
